// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using ThanyMarcus.Cloud.Api.Infrastructure.Database;

#nullable disable

namespace ThanyMarcus.Cloud.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CloudDbContext))]
    [Migration("20260530144012_NotesEmbeddingHnswPartial")]
    partial class NotesEmbeddingHnswPartial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Entities.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Aliases")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("aliases")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("CanonicalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_name");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(256)")
                        .HasColumnName("embedding");

                    b.Property<Guid?>("HubNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("hub_note_id");

                    b.Property<bool>("IsProvisional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_provisional");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("MentionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("mention_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VaultFolder")
                        .HasColumnType("text")
                        .HasColumnName("vault_folder");

                    b.HasKey("Id")
                        .HasName("pk_entities");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_entities_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Kind", "CanonicalName")
                        .IsUnique()
                        .HasDatabaseName("ix_entities_kind_canonical_name")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Kind", "Source")
                        .HasDatabaseName("ix_entities_kind_source");

                    b.ToTable("entities", null, t =>
                        {
                            t.HasCheckConstraint("ck_entities_kind", "kind IN ('person','organization','project','place','concept','other')");

                            t.HasCheckConstraint("ck_entities_source", "source IN ('user','llm')");
                        });
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Entities.Mention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnchorText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("anchor_text");

                    b.Property<float?>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EndOffset")
                        .HasColumnType("integer")
                        .HasColumnName("end_offset");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<int>("StartOffset")
                        .HasColumnType("integer")
                        .HasColumnName("start_offset");

                    b.HasKey("Id")
                        .HasName("pk_mentions");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_mentions_entity_id");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_mentions_note_id");

                    b.ToTable("mentions", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Ingest.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ClientAttachmentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_attachment_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Extra")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("extra")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("ExtractionCacheKey")
                        .HasColumnType("text")
                        .HasColumnName("extraction_cache_key");

                    b.Property<string>("ExtractionError")
                        .HasColumnType("text")
                        .HasColumnName("extraction_error");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("extraction_status");

                    b.Property<string>("Filename")
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<Guid?>("ParentAttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_attachment_id");

                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_bucket");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_provider");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_attachments_note_id");

                    b.HasIndex("ParentAttachmentId")
                        .HasDatabaseName("ix_attachments_parent");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_storage_key");

                    b.HasIndex("NoteId", "ClientAttachmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_note_id_client_attachment_id");

                    b.HasIndex("Sha256", "ExtractionCacheKey")
                        .HasDatabaseName("ix_attachments_cache")
                        .HasFilter("extracted_text IS NOT NULL");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_attachments_extraction_status", "extraction_status IN ('pending','extracted','skipped','failed')");

                            t.HasCheckConstraint("ck_attachments_kind", "kind IN ('url','image','voice','file')");

                            t.HasCheckConstraint("ck_attachments_status", "status IN ('pending','awaiting_upload','uploaded')");
                        });
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Ingest.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHash")
                        .HasColumnType("text")
                        .HasColumnName("body_hash");

                    b.Property<string>("BodyInput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_input");

                    b.Property<string>("BodyOutput")
                        .HasColumnType("text")
                        .HasColumnName("body_output");

                    b.Property<Instant>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("ClientNoteId")
                        .HasColumnType("text")
                        .HasColumnName("client_note_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(256)")
                        .HasColumnName("embedding");

                    b.Property<Guid?>("HubEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("hub_entity_id");

                    b.Property<bool>("IsHub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_hub");

                    b.Property<string>("LlmMode")
                        .HasColumnType("text")
                        .HasColumnName("llm_mode");

                    b.Property<string>("PrivacyMode")
                        .HasColumnType("text")
                        .HasColumnName("privacy_mode");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<JsonDocument>("Provenance")
                        .HasColumnType("jsonb")
                        .HasColumnName("provenance");

                    b.Property<string>("PublicModel")
                        .HasColumnType("text")
                        .HasColumnName("public_model");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text")
                        .HasColumnName("relative_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SynthesisCacheKey")
                        .HasColumnType("text")
                        .HasColumnName("synthesis_cache_key");

                    b.Property<string>("SynthesisCacheValue")
                        .HasColumnType("text")
                        .HasColumnName("synthesis_cache_value");

                    b.Property<string>("SynthesisPreset")
                        .HasColumnType("text")
                        .HasColumnName("synthesis_preset");

                    b.Property<string>("SynthesisPromptBody")
                        .HasColumnType("text")
                        .HasColumnName("synthesis_prompt_body");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<long>("TransitionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("transition_version");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasIndex("ClientNoteId")
                        .IsUnique()
                        .HasDatabaseName("ix_notes_client_note_id")
                        .HasFilter("client_note_id IS NOT NULL");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_notes_embedding")
                        .HasFilter("deleted_at IS NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("HubEntityId")
                        .HasDatabaseName("ix_notes_hub_entity")
                        .HasFilter("is_hub");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_notes_project");

                    b.HasIndex("SynthesisCacheKey")
                        .HasDatabaseName("ix_notes_synthesis_cache_key")
                        .HasFilter("synthesis_cache_key IS NOT NULL");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_notes_updated_at")
                        .HasFilter("deleted_at IS NULL OR status = 'ready'");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_notes_status_updated_at");

                    b.ToTable("notes", null, t =>
                        {
                            t.HasCheckConstraint("ck_notes_llm_mode", "llm_mode IS NULL OR llm_mode IN ('safe','unsafe_anthropic','unsafe_openai')");

                            t.HasCheckConstraint("ck_notes_status", "status IN ('pending','processing','ready','failed')");
                        });
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.PluginAuth.PluginToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_plugin_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_plugin_tokens_token_hash");

                    b.ToTable("plugin_tokens", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Processing.ExtractionTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.Property<short>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("attempts");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("EventsLog")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("events_log")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Instant?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("IngestJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingest_job_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Instant?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("text")
                        .HasColumnName("lease_owner");

                    b.Property<Instant>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Instant?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TargetSidecar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_sidecar");

                    b.Property<long>("TransitionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("transition_version");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_extraction_tasks");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_extraction_tasks_attachment_id");

                    b.HasIndex("IngestJobId")
                        .HasDatabaseName("ix_extraction_tasks_ingest_job_id");

                    b.HasIndex("TargetSidecar", "Status", "ScheduledAt")
                        .HasDatabaseName("ix_extraction_tasks_claim")
                        .HasFilter("status IN ('queued','processing')");

                    b.ToTable("extraction_tasks", null, t =>
                        {
                            t.HasCheckConstraint("ck_extraction_tasks_status", "status IN ('queued','processing','succeeded','failed','skipped')");

                            t.HasCheckConstraint("ck_extraction_tasks_target_sidecar", "target_sidecar IN ('ollama','docling','parakeet','url','video')");
                        });
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Processing.IngestJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Attempts")
                        .HasColumnType("smallint")
                        .HasColumnName("attempts");

                    b.Property<short>("ConsecutiveCrashes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("consecutive_crashes");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("EventsLog")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("events_log")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Instant?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("capture")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Instant?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("text")
                        .HasColumnName("lease_owner");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<Instant>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Instant?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("TransitionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("transition_version");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ingest_jobs");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("ix_ingest_jobs_queued_scheduled_at")
                        .HasFilter("status = 'queued'");

                    b.HasIndex(new[] { "NoteId" }, "ix_ingest_jobs_active_per_note")
                        .IsUnique()
                        .HasDatabaseName("ix_ingest_jobs_active_per_note")
                        .HasFilter("status NOT IN ('succeeded','failed_extraction','failed_composition','failed_entities','failed_route','failed_synthesis','failed_embedding','dead_lettered','cancelled')");

                    b.HasIndex(new[] { "NoteId" }, "ix_ingest_jobs_note_id")
                        .HasDatabaseName("ix_ingest_jobs_note_id");

                    b.ToTable("ingest_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_ingest_jobs_kind", "kind IN ('capture','hub_regen','reprocess','user_edit_embed')");

                            t.HasCheckConstraint("ck_ingest_jobs_status", "status IN ('queued','extracting_attachments','composing','extracting_entities','routing','synthesizing','embedding','succeeded','failed_extraction','failed_composition','failed_entities','failed_route','failed_synthesis','failed_embedding','dead_lettered','cancelled')");
                        });
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Settings.CloudSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id");

                    b.Property<byte[]>("EncryptedExternalApiKey")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_external_api_key");

                    b.Property<string>("LlmMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("safe")
                        .HasColumnName("llm_mode");

                    b.Property<string>("LlmModel")
                        .HasColumnType("text")
                        .HasColumnName("llm_model");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cloud_settings");

                    b.ToTable("cloud_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_cloud_settings_llm_mode", "llm_mode IN ('safe','unsafe_anthropic','unsafe_openai')");

                            t.HasCheckConstraint("ck_cloud_settings_singleton", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LlmMode = "safe",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17790624000000000L)
                        });
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Entities.Mention", b =>
                {
                    b.HasOne("ThanyMarcus.Cloud.Api.Features.Entities.Entity", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mentions_entities_entity_id");

                    b.HasOne("ThanyMarcus.Cloud.Api.Features.Ingest.Note", null)
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mentions_notes_note_id");
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Ingest.Attachment", b =>
                {
                    b.HasOne("ThanyMarcus.Cloud.Api.Features.Ingest.Note", null)
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_notes_note_id");

                    b.HasOne("ThanyMarcus.Cloud.Api.Features.Ingest.Attachment", null)
                        .WithMany()
                        .HasForeignKey("ParentAttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_attachments_attachments_parent_attachment_id");
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Ingest.Note", b =>
                {
                    b.HasOne("ThanyMarcus.Cloud.Api.Features.Entities.Entity", null)
                        .WithMany()
                        .HasForeignKey("HubEntityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notes_entities_hub_entity_id");

                    b.HasOne("ThanyMarcus.Cloud.Api.Features.Entities.Entity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notes_entities_project_id");
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Processing.ExtractionTask", b =>
                {
                    b.HasOne("ThanyMarcus.Cloud.Api.Features.Ingest.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extraction_tasks_attachments_attachment_id");

                    b.HasOne("ThanyMarcus.Cloud.Api.Features.Processing.IngestJob", null)
                        .WithMany()
                        .HasForeignKey("IngestJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_extraction_tasks_ingest_jobs_ingest_job_id");
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Processing.IngestJob", b =>
                {
                    b.HasOne("ThanyMarcus.Cloud.Api.Features.Ingest.Note", null)
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingest_jobs_notes_note_id");
                });
#pragma warning restore 612, 618
        }
    }
}
