// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThanyMarcus.Cloud.Api.Infrastructure.Database;

#nullable disable

namespace ThanyMarcus.Cloud.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CloudDbContext))]
    [Migration("20260517215436_CompositeIngestSpine")]
    partial class CompositeIngestSpine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Ingest.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ClientAttachmentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_attachment_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Extra")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("extra")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("ExtractionError")
                        .HasColumnType("text")
                        .HasColumnName("extraction_error");

                    b.Property<string>("ExtractionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("extraction_status");

                    b.Property<string>("Filename")
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StorageBucket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_bucket");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_provider");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_attachments_note_id");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_storage_key");

                    b.HasIndex("NoteId", "ClientAttachmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_note_id_client_attachment_id");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_attachments_extraction_status", "extraction_status IN ('pending','extracted','skipped','failed')");

                            t.HasCheckConstraint("ck_attachments_kind", "kind IN ('url','image','voice','file')");

                            t.HasCheckConstraint("ck_attachments_status", "status IN ('pending','awaiting_upload','uploaded')");
                        });
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Ingest.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyInput")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_input");

                    b.Property<string>("BodyOutput")
                        .HasColumnType("text")
                        .HasColumnName("body_output");

                    b.Property<Instant>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("ClientNoteId")
                        .HasColumnType("text")
                        .HasColumnName("client_note_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LlmMode")
                        .HasColumnType("text")
                        .HasColumnName("llm_mode");

                    b.Property<JsonDocument>("Provenance")
                        .HasColumnType("jsonb")
                        .HasColumnName("provenance");

                    b.Property<string>("RelativePath")
                        .HasColumnType("text")
                        .HasColumnName("relative_path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedProject")
                        .HasColumnType("text")
                        .HasColumnName("suggested_project");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notes");

                    b.HasIndex("ClientNoteId")
                        .IsUnique()
                        .HasDatabaseName("ix_notes_client_note_id");

                    b.HasIndex("Status", "UpdatedAt")
                        .HasDatabaseName("ix_notes_status_updated_at");

                    b.ToTable("notes", null, t =>
                        {
                            t.HasCheckConstraint("ck_notes_llm_mode", "llm_mode IS NULL OR llm_mode IN ('safe','unsafe_anthropic','unsafe_openai')");

                            t.HasCheckConstraint("ck_notes_status", "status IN ('pending','processing','ready','failed')");
                        });
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.PluginAuth.PluginToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_plugin_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_plugin_tokens_token_hash");

                    b.ToTable("plugin_tokens", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Processing.IngestJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Attempts")
                        .HasColumnType("smallint")
                        .HasColumnName("attempts");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Instant?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("text")
                        .HasColumnName("lease_owner");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<Instant>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Instant?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ingest_jobs");

                    b.HasIndex("NoteId")
                        .HasDatabaseName("ix_ingest_jobs_note_id");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("ix_ingest_jobs_queued_scheduled_at")
                        .HasFilter("status = 'queued'");

                    b.ToTable("ingest_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_ingest_jobs_status", "status IN ('queued','processing','succeeded','dead_lettered')");
                        });
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Settings.CloudSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id");

                    b.Property<byte[]>("EncryptedExternalApiKey")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_external_api_key");

                    b.Property<string>("LlmMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("safe")
                        .HasColumnName("llm_mode");

                    b.Property<string>("LlmModel")
                        .HasColumnType("text")
                        .HasColumnName("llm_model");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cloud_settings");

                    b.ToTable("cloud_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_cloud_settings_llm_mode", "llm_mode IN ('safe','unsafe_anthropic','unsafe_openai')");

                            t.HasCheckConstraint("ck_cloud_settings_singleton", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LlmMode = "safe",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17790624000000000L)
                        });
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Ingest.Attachment", b =>
                {
                    b.HasOne("ThanyMarcus.Cloud.Api.Features.Ingest.Note", null)
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_notes_note_id");
                });

            modelBuilder.Entity("ThanyMarcus.Cloud.Api.Features.Processing.IngestJob", b =>
                {
                    b.HasOne("ThanyMarcus.Cloud.Api.Features.Ingest.Note", null)
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ingest_jobs_notes_note_id");
                });
#pragma warning restore 612, 618
        }
    }
}
