<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ThanyMarcus.Portal.Tests</RootNamespace>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="CloudInit\Fixtures\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="NodaTime.Testing" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ThanyMarcus.Portal.Api\ThanyMarcus.Portal.Api.csproj" />
    <ProjectReference Include="..\..\src\ThanyMarcus.Portal.SagaWorker\ThanyMarcus.Portal.SagaWorker.csproj" />
  </ItemGroup>

</Project>
