<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>thany-marcus-cloud-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ThanyMarcus.Cloud.UnitTests" />
    <InternalsVisibleTo Include="ThanyMarcus.Cloud.IntegrationTests" />
    <InternalsVisibleTo Include="ThanyMarcus.Cloud.TestSupport" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />

    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />

    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Process" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" />

    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Pgvector" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" />

    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="CoenM.ImageSharp.ImageHash" />

    <PackageReference Include="PdfPig" />
    <PackageReference Include="NAudio.Core" />

    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
    <PackageReference Include="Tokenizers.DotNet" />
    <PackageReference Include="Tokenizers.DotNet.runtime.osx-arm64" />
    <PackageReference Include="Tokenizers.DotNet.runtime.linux-x64" />

    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThanyMarcus.Shared\ThanyMarcus.Shared.csproj" />
  </ItemGroup>

</Project>
