<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>thany-marcus-saga-worker</UserSecretsId>
    <RootNamespace>ThanyMarcus.Portal.SagaWorker</RootNamespace>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ThanyMarcus.Portal.UnitTests" />
    <InternalsVisibleTo Include="ThanyMarcus.Portal.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Process" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="AWSSDK.S3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThanyMarcus.Portal.Api\ThanyMarcus.Portal.Api.csproj">
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

</Project>
