// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThanyMarcus.Portal.Api.Infrastructure.Database;

#nullable disable

namespace ThanyMarcus.Portal.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20260604083618_AddSagaCredentialGrants")]
    partial class AddSagaCredentialGrants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.AuthLockout", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<short>("FailedCount")
                        .HasColumnType("smallint")
                        .HasColumnName("failed_count");

                    b.Property<Instant>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<Instant?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.HasKey("UserId", "Kind")
                        .HasName("pk_auth_lockouts");

                    b.ToTable("auth_lockouts", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.DigitalOcean.DigitalOceanOAuthConnection", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("AccessCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_ciphertext");

                    b.Property<Instant>("AccessExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_expires_at");

                    b.Property<byte[]>("AccessNonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_nonce");

                    b.Property<byte[]>("AccessTag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_tag");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("connected")
                        .HasColumnName("connection_status");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("RefreshCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_ciphertext");

                    b.Property<byte[]>("RefreshNonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_nonce");

                    b.Property<byte[]>("RefreshTag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_tag");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_digitalocean_oauth_connections");

                    b.ToTable("digitalocean_oauth_connections", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.EmergencyKit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HashedString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_string");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Instant?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<JsonDocument>("WrapArgon2Params")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("wrap_argon2params");

                    b.Property<byte[]>("WrapArgon2Salt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrap_argon2salt");

                    b.Property<byte[]>("WrapNonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrap_nonce");

                    b.Property<byte[]>("WrapTag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrap_tag");

                    b.Property<byte[]>("WrappedDek")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_dek");

                    b.HasKey("Id")
                        .HasName("pk_emergency_kits");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_emergency_kits_active_per_user")
                        .HasFilter("used_at IS NULL AND revoked_at IS NULL");

                    b.ToTable("emergency_kits", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.EncryptedProviderToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("tag");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_encrypted_provider_tokens");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_encrypted_provider_tokens_user_id_provider");

                    b.ToTable("encrypted_provider_tokens", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.Passkey.PasskeyCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Aaguid")
                        .HasColumnType("uuid")
                        .HasColumnName("aaguid");

                    b.Property<string>("AuthenticatorName")
                        .HasColumnType("text")
                        .HasColumnName("authenticator_name");

                    b.Property<bool>("BackedUp")
                        .HasColumnType("boolean")
                        .HasColumnName("backed_up");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("credential_id");

                    b.Property<Instant?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sign_count");

                    b.PrimitiveCollection<string[]>("Transports")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("transports");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_passkey_credentials");

                    b.HasIndex("CredentialId")
                        .IsUnique()
                        .HasDatabaseName("ix_passkey_credentials_credential_id")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_passkey_credentials_user_id")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("passkey_credentials", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.StepUp.StepUpUnlock", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("EncryptedDek")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_dek");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Instant>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.HasKey("UserId")
                        .HasName("pk_step_up_unlocks");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_step_up_unlocks_expires_at");

                    b.ToTable("step_up_unlocks", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.TotpBackupCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HashedCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_code");

                    b.Property<Instant?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_totp_backup_codes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_totp_backup_codes_user_id");

                    b.ToTable("totp_backup_codes", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.TotpSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<Instant?>("EnabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enabled_at");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("tag");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_totp_secrets");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_totp_secrets_user_id");

                    b.ToTable("totp_secrets", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSubject")
                        .HasColumnType("text")
                        .HasColumnName("google_subject");

                    b.Property<Instant>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<JsonDocument>("PassphraseArgon2Params")
                        .HasColumnType("jsonb")
                        .HasColumnName("passphrase_argon2params");

                    b.Property<byte[]>("PassphraseArgon2Salt")
                        .HasColumnType("bytea")
                        .HasColumnName("passphrase_argon2salt");

                    b.Property<Instant?>("PassphraseSetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("passphrase_set_at");

                    b.Property<byte[]>("PassphraseWrapNonce")
                        .HasColumnType("bytea")
                        .HasColumnName("passphrase_wrap_nonce");

                    b.Property<byte[]>("PassphraseWrapTag")
                        .HasColumnType("bytea")
                        .HasColumnName("passphrase_wrap_tag");

                    b.Property<byte[]>("PassphraseWrappedDek")
                        .HasColumnType("bytea")
                        .HasColumnName("passphrase_wrapped_dek");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<Instant?>("SessionsInvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sessions_invalidated_at");

                    b.Property<byte[]>("TotpWrapNonce")
                        .HasColumnType("bytea")
                        .HasColumnName("totp_wrap_nonce");

                    b.Property<byte[]>("TotpWrapTag")
                        .HasColumnType("bytea")
                        .HasColumnName("totp_wrap_tag");

                    b.Property<byte[]>("TotpWrappedDek")
                        .HasColumnType("bytea")
                        .HasColumnName("totp_wrapped_dek");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GoogleSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_subject");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.CloudManagement.Cloud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("AdminStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("admin_started_at");

                    b.Property<Instant?>("ApplyStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("apply_started_at");

                    b.Property<Instant?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancel_requested_at");

                    b.Property<Instant?>("CertStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cert_started_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DestroyedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("destroyed_at");

                    b.Property<Instant?>("DnsStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dns_started_at");

                    b.Property<byte[]>("EncryptedCloudAdminToken")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_cloud_admin_token");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hostname");

                    b.Property<Instant?>("MintingSpacesStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("minting_spaces_started_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant?>("PlanStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plan_started_at");

                    b.Property<string>("PriceCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("USD")
                        .HasColumnName("price_currency");

                    b.Property<decimal?>("PriceHourlyUsd")
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("price_hourly_usd");

                    b.Property<decimal?>("PriceMonthlyUsd")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("price_monthly_usd");

                    b.Property<Instant?>("PricedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("priced_at");

                    b.Property<string>("PricedSource")
                        .HasColumnType("text")
                        .HasColumnName("priced_source");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<Guid?>("ProviderTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_token_id");

                    b.Property<Instant?>("ProvisioningCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provisioning_completed_at");

                    b.Property<string>("ProvisioningError")
                        .HasColumnType("text")
                        .HasColumnName("provisioning_error");

                    b.Property<string>("ProvisioningStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provisioning_status");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("Subdomain")
                        .HasColumnType("text")
                        .HasColumnName("subdomain");

                    b.Property<string>("TerraformWorkspace")
                        .HasColumnType("text")
                        .HasColumnName("terraform_workspace");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VmIp")
                        .HasColumnType("text")
                        .HasColumnName("vm_ip");

                    b.HasKey("Id")
                        .HasName("pk_clouds");

                    b.HasIndex("Hostname")
                        .IsUnique()
                        .HasDatabaseName("ix_clouds_hostname");

                    b.HasIndex("ProviderTokenId")
                        .HasDatabaseName("ix_clouds_provider_token_id");

                    b.HasIndex("Subdomain")
                        .IsUnique()
                        .HasDatabaseName("ix_clouds_subdomain");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_clouds_user_id");

                    b.ToTable("clouds", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.CloudManagement.PluginTokenMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CloudId")
                        .HasColumnType("uuid")
                        .HasColumnName("cloud_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plugin_token_metadata");

                    b.HasIndex("CloudId")
                        .HasDatabaseName("ix_plugin_token_metadata_cloud_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_plugin_token_metadata_token_hash");

                    b.ToTable("plugin_token_metadata", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.CloudManagement.Secrets.CloudSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<Guid>("CloudId")
                        .HasColumnType("uuid")
                        .HasColumnName("cloud_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("tag");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cloud_secrets");

                    b.HasIndex("CloudId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_cloud_secrets_cloud_id_kind");

                    b.ToTable("cloud_secrets", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Provisioning.ProvisioningJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AttemptCount")
                        .HasColumnType("smallint")
                        .HasColumnName("attempt_count");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text")
                        .HasColumnName("claimed_by");

                    b.Property<Guid>("CloudId")
                        .HasColumnType("uuid")
                        .HasColumnName("cloud_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EnrollmentToken")
                        .HasColumnType("text")
                        .HasColumnName("enrollment_token");

                    b.Property<JsonDocument>("EventsLog")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("events_log")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Instant?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Instant>("NextVisibleAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_visible_at");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Instant?>("PhaseStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phase_started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<JsonDocument>("TfOutputs")
                        .HasColumnType("jsonb")
                        .HasColumnName("tf_outputs");

                    b.Property<long>("TransitionVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("transition_version");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_provisioning_jobs");

                    b.HasIndex("CloudId")
                        .HasDatabaseName("ix_provisioning_jobs_cloud_id");

                    b.HasIndex("NextVisibleAt")
                        .HasDatabaseName("ix_provisioning_jobs_active_next_visible_at")
                        .HasFilter("status NOT IN ('succeeded','failed_tf','failed_dns','failed_callback','failed_cert','failed_destroy','cancelled','rolled_back')");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_provisioning_jobs_user_create_active")
                        .HasFilter("kind = 'create' AND status NOT IN ('succeeded','failed_tf','failed_dns','failed_callback','failed_cert','failed_destroy','cancelled','rolled_back')");

                    b.ToTable("provisioning_jobs", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Provisioning.SagaCredentials.SagaCredentialGrant", b =>
                {
                    b.Property<Guid>("CloudId")
                        .HasColumnType("uuid")
                        .HasColumnName("cloud_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("SealedDek")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sealed_dek");

                    b.HasKey("CloudId")
                        .HasName("pk_saga_credential_grants");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_saga_credential_grants_expires_at");

                    b.ToTable("saga_credential_grants", (string)null);
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.AuthLockout", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_lockouts_users_user_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.DigitalOcean.DigitalOceanOAuthConnection", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_digitalocean_oauth_connections_users_user_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.EmergencyKit", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_emergency_kits_users_user_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.EncryptedProviderToken", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_encrypted_provider_tokens_users_user_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.Passkey.PasskeyCredential", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_passkey_credentials_users_user_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.StepUp.StepUpUnlock", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_step_up_unlocks_users_user_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.TotpBackupCode", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_totp_backup_codes_users_user_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Auth.TotpSecret", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.Auth.User", null)
                        .WithOne()
                        .HasForeignKey("ThanyMarcus.Portal.Api.Features.Auth.TotpSecret", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_totp_secrets_users_user_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.CloudManagement.Cloud", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.Auth.EncryptedProviderToken", null)
                        .WithMany()
                        .HasForeignKey("ProviderTokenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clouds_encrypted_provider_tokens_provider_token_id");

                    b.HasOne("ThanyMarcus.Portal.Api.Features.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clouds_users_user_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.CloudManagement.PluginTokenMetadata", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.CloudManagement.Cloud", null)
                        .WithMany()
                        .HasForeignKey("CloudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plugin_token_metadata_clouds_cloud_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.CloudManagement.Secrets.CloudSecret", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.CloudManagement.Cloud", null)
                        .WithMany()
                        .HasForeignKey("CloudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cloud_secrets_clouds_cloud_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Provisioning.ProvisioningJob", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.CloudManagement.Cloud", null)
                        .WithMany()
                        .HasForeignKey("CloudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_provisioning_jobs_clouds_cloud_id");

                    b.HasOne("ThanyMarcus.Portal.Api.Features.Auth.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_provisioning_jobs_users_user_id");
                });

            modelBuilder.Entity("ThanyMarcus.Portal.Api.Features.Provisioning.SagaCredentials.SagaCredentialGrant", b =>
                {
                    b.HasOne("ThanyMarcus.Portal.Api.Features.CloudManagement.Cloud", null)
                        .WithMany()
                        .HasForeignKey("CloudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saga_credential_grants_clouds_cloud_id");
                });
#pragma warning restore 612, 618
        }
    }
}
